#!/bin/sh

rm -rf _site

LC_ALL="en_US.UTF-8" \
bundle exec jekyll build --config _config_en.yml

htmlproofer ./_site --allow_hash_href --file_ignore /assets/ --empty_alt_ignore --http_status_ignore 999

rm -rf _site

LC_ALL="en_US.UTF-8" \
bundle exec jekyll build --config _config_fr.yml

htmlproofer ./_site --allow_hash_href --file_ignore /assets/ --empty_alt_ignore --http_status_ignore 999