name: Staging review apps

on:
  - pull_request

env:
  GITHUB_SHA: ${{ github.sha }}
  IMAGE: website-staging
  REGISTRY: 773858180673.dkr.ecr.ca-central-1.amazonaws.com
  ROLE_ARN: arn:aws:iam::773858180673:role/website-staging-execution-role

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Set envs
        run: echo "PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build container
        run: |
          docker build -t $REGISTRY/$IMAGE:$PR_NUMBER .

      - name: Configure AWS credentials
        id: aws-creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push containers to ECR
        run: |
          docker push $REGISTRY/$IMAGE:$PR_NUMBER

      - name: Logout of Amazon ECR
        run: docker logout $REGISTRY

      - name: Create lambda function
        run: |
          if aws lambda get-function --function-name website-staging-$PR_NUMBER > /dev/null 2>&1; then
            aws lambda update-function-code \
              --function-name website-staging-$PR_NUMBER \
              --image-uri $REGISTRY/$IMAGE:$PR_NUMBER > /dev/null 2>&1
          else
            aws lambda create-function \
              --function-name website-staging-$PR_NUMBER \
              --package-type Image \
              --role $ROLE_ARN \
              --code ImageUri=$REGISTRY/$IMAGE:$PR_NUMBER > /dev/null 2>&1

              aws lambda wait function-active --function-name website-staging-$PR_NUMBER
              sleep 30
              aws lambda create-function-url-config --region ca-central-1 --function-name website-staging-$PR_NUMBER --auth-type NONE
          fi
