name: Generate SBOM

on:
  pull_request:
    branches:
      - main
    paths:
      - package-lock.json
      - .github/workflows/generate-sbom.yaml
  push:
    branches:
      - main
    paths:
      - package-lock.json
      - .github/workflows/generate-sbom.yaml

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate front-end SBOM
        uses: cds-snc/security-tools/.github/actions/generate-sbom@4c6b386722985552f3f008d04279a3f01402cc35 # renovate: tag=v1
        with:
          dependency_track_api_key: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}
          project_name: digital-canada-ca/website
          project_type: node          
