name: "Terraform Apply Production"

on:
  push:
    branches:
      - main
    paths:
      - "terragrunt/**"
      - ".github/workflows/tf_apply_production.yml"

env:
  AWS_REGION: ca-central-1
  TERRAFORM_VERSION: 1.4.6
  TERRAGRUNT_VERSION: 0.45.11
  CONFTEST_VERSION: 0.42.1

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write
  
jobs:
  terragrunt-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: setup terraform tools
        uses: cds-snc/terraform-tools-setup@v1

      - name: configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@ef93a73b1313f148011965ef7361f667f371f58b # v3.0.0
        with:
          role-to-assume: arn:aws:iam::521732289257:role/digital-canada-ca-apply  # TF apply
          role-session-name: TFApply
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Apply S3
        working-directory: terragrunt/env/production/s3
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Terraform Apply Hosted Zone
        working-directory: terragrunt/env/production/hosted_zone
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Terraform Apply Cloudfront
        working-directory: terragrunt/env/production/cloudfront
        run: terragrunt apply --terragrunt-non-interactive -auto-approve  