name: "Terraform Plan"

on:
  workflow_dispatch:
  pull_request:
    paths:
    - "terragrunt/**"
    - ".github/workflows/tf_plan_production.yml"

env:
  AWS_REGION: ca-central-1
  TERRAFORM_VERSION: 1.4.6
  TERRAGRUNT_VERSION: 0.45.11
  CONFTEST_VERSION: 0.42.1

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write

jobs:
  terragrunt-plan:
    strategy:
      fail-fast: false
      matrix:
        include:
          - module: s3
          - module: hosted_zone
          - module: cloudfront 

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - name: set up terraform tools
      uses: cds-snc/terraform-tools-setup@v1

    - name: configure aws credentials using OIDC
      uses: aws-actions/configure-aws-credentials@e1e17a757e536f70e52b5a12b2e8d1d1c60e04ef # v2.0.0
      with:
        role-to-assume: arn:aws:iam::521732289257:role/digital-canada-ca-plan   # TF plan
        role-session-name: TFPlan
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Plan
      uses: cds-snc/terraform-plan@7f4ce4a4bdffaba639d32a45272804e37a569408 # v3.0.6
      with:
        comment-delete: true
        comment-title: "Production: ${{ matrix.module }}"
        directory: terragrunt/env/production/${{ matrix.module }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        terragrunt: true   

